stages:
    - runSCAScanUsingSnykk

run-sca-job:
    stage: runSCAScanUsingSnykk
    image: maven:3.8.5-openjdk-11-slim
    script: |
      SNYK_TOKEN='2f4afa39-c493-4c6d-b34e-080c1a8f9014'
      export SNYK_TOKEN
      mvn snyk:test -fn
